#!/bin/bash
START=$(date +%s)
echo $START
while true
  do
    if (($((($(date +%s))-($START))) == 0))
      then
        '/home/Local_address_Filename'
        START=$((($START)+180))
        echo $START
      fi
    done
